import daisyui from "daisyui";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        "neutral-glass": {
          primary: "#5B6DFF",
          "primary-content": "#FFFFFF",
          secondary: "#36D6B5",
          "secondary-content": "#FFFFFF",
          accent: "#FF6B9D",
          "accent-content": "#FFFFFF",
          neutral: "#2A2B3D",
          "neutral-content": "#E4E6F0",
          "base-100": "#1E1F2E",
          "base-200": "#252638",
          "base-300": "#343550",
          "base-content": "#F0F1F5",
          info: "#5BC0EB",
          success: "#36D6B5",
          warning: "#FFD166",
          error: "#EF476F",
        },
      },
      {
        "midnight-gamer": {
          primary: "#00F0FF",
          secondary: "#7B2FFF",
          accent: "#FF3D71",
          neutral: "#171728",
          "base-100": "#0D0D1A",
          "base-200": "#141428",
          "base-300": "#1E1E3C",
          "base-content": "#E0E0FF",
        },
      },
      {
        "ocean-storm": {
          primary: "#0077B6",
          secondary: "#00B4D8",
          accent: "#90E0EF",
          neutral: "#112038",
          "base-100": "#0A1628",
          "base-200": "#0F2035",
          "base-300": "#1A3050",
          "base-content": "#CAF0F8",
        },
      },
      {
        "cyber-punk": {
          primary: "#F7E733",
          secondary: "#FF2E97",
          accent: "#00FF88",
          neutral: "#211530",
          "base-100": "#120716",
          "base-200": "#1A0E22",
          "base-300": "#2D1B3D",
          "base-content": "#F0E6FF",
        },
      },
      {
        "forest-warrior": {
          primary: "#4CAF50",
          secondary: "#8BC34A",
          accent: "#FF9800",
          neutral: "#252b1b",
          "base-100": "#1A1E12",
          "base-200": "#222818",
          "base-300": "#2E3520",
          "base-content": "#E8F5E9",
        },
      },
      {
        "sakura-dream": {
          primary: "#FF8FAB",
          "primary-content": "#FFFFFF",
          secondary: "#FFB3C6",
          accent: "#FF5C8A",
          "accent-content": "#FFFFFF",
          neutral: "#FFEBEB",
          "base-100": "#FFF0F3",
          "base-200": "#FFE0E6",
          "base-300": "#FFCDD5",
          "base-content": "#3D2C2E",
        },
      },
      {
        "lavender-cloud": {
          primary: "#B48EFF",
          "primary-content": "#FFFFFF",
          secondary: "#E0C3FC",
          accent: "#FF9CEE",
          neural: "#EFE6FF",
          "base-100": "#F5F0FF",
          "base-200": "#EDE4FF",
          "base-300": "#DDD0F5",
          "base-content": "#2D2640",
        },
      },
      {
        "peach-blossom": {
          primary: "#FF8C69",
          "primary-content": "#FFFFFF",
          secondary: "#FFB085",
          accent: "#FF6B6B",
          "accent-content": "#FFFFFF",
          neutral: "#FFEDE0",
          "base-100": "#FFF8F0",
          "base-200": "#FFE8D6",
          "base-300": "#FFDBC2",
          "base-content": "#3D2E28",
        },
      },
      {
        "mint-candy": {
          primary: "#4ECDC4",
          "primary-content": "#FFFFFF",
          secondary: "#A8E6CF",
          accent: "#FF6B9D",
          "accent-content": "#FFFFFF",
          neutral: "#E0F5EB",
          "base-100": "#F0FFF8",
          "base-200": "#E0F5EC",
          "base-300": "#C8EBD8",
          "base-content": "#1E3A32",
        },
      },
    ],
  },
};
