import { axiosInstance } from "./axios";
import toast from "react-hot-toast";

// Fetch ICE Servers (STUN/TURN) from our backend which calls Metered.ca
export const fetchIceServers = async () => {
  try {
    const res = await axiosInstance.get("/calls/ice-servers");
    return res.data;
  } catch (error) {
    console.error("Failed to fetch ICE servers, using public STUN fallback.", error);
    // Fallback to public Google STUN if backend or Metered fails
    return [
      { urls: "stun:stun.l.google.com:19302" },
      { urls: "stun:stun1.l.google.com:19302" }
    ];
  }
};

// Create a new RTCPeerConnection
export const createPeerConnection = (iceServers, onIceCandidate, onTrack, onIceConnectionStateChange) => {
  const pc = new RTCPeerConnection({ iceServers });

  // Handle local ICE candidates generated by the browser
  pc.onicecandidate = (event) => {
    if (event.candidate) {
      onIceCandidate(event.candidate);
    }
  };

  // Handle remote media tracks arriving
  pc.ontrack = (event) => {
    onTrack(event.streams[0]);
  };

  // Monitor connection health (calling -> connected -> disconnected -> failed)
  pc.oniceconnectionstatechange = () => {
    onIceConnectionStateChange(pc.iceConnectionState);
  };

  return pc;
};

// Generate Offer SDP
export const createOffer = async (pc) => {
  try {
    const offer = await pc.createOffer();
    await pc.setLocalDescription(offer);
    return offer;
  } catch (error) {
    console.error("Error creating offer SDP:", error);
    throw error;
  }
};

// Generate Answer SDP in response to an Offer
export const createAnswer = async (pc, offerSdp) => {
  try {
    await pc.setRemoteDescription(new RTCSessionDescription(offerSdp));
    const answer = await pc.createAnswer();
    await pc.setLocalDescription(answer);
    return answer;
  } catch (error) {
    console.error("Error creating answer SDP:", error);
    throw error;
  }
};

// Safely request microphone/camera permissions with graceful error handling
export const getUserMediaSafe = async (constraints) => {
  try {
    const stream = await navigator.mediaDevices.getUserMedia(constraints);
    return stream;
  } catch (error) {
    console.error("Error accessing media devices:", error);
    
    // Map standard WebRTC explicit errors
    if (error.name === "NotAllowedError" || error.name === "PermissionDeniedError") {
      toast.error("Bạn đã từ chối quyền truy cập Micro/Camera. Vui lòng cấp quyền trong cài đặt trình duyệt để tiếp tục.");
    } else if (error.name === "NotFoundError" || error.name === "DevicesNotFoundError") {
      toast.error("Không tìm thấy Micro hoặc Camera trên thiết bị của bạn.");
    } else if (error.name === "NotReadableError" || error.name === "TrackStartError") {
      toast.error("Micro/Camera đang bị ứng dụng khác sử dụng.");
    } else {
      toast.error("Lỗi không xác định khi truy cập Micro/Camera.");
    }
    
    throw error; // Re-throw to be handled by the caller UI (e.g. show DeviceLobby)
  }
};

// Cleanup function to completely strip a connection
export const cleanupConnection = (pc, stream) => {
  if (stream) {
    stream.getTracks().forEach(track => {
      track.stop(); // Stops the camera light and mic
    });
  }
  
  if (pc) {
    // Remove listeners to prevent memory leaks
    pc.onicecandidate = null;
    pc.ontrack = null;
    pc.oniceconnectionstatechange = null;
    pc.close();
  }
};
